// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package database

import (
	"database/sql"
)

type Alias struct {
	ID        int64
	AliasText sql.NullString
}

type AliasDesc struct {
	ID            int64
	AliasID       sql.NullInt64
	DescriptionID sql.NullInt64
}

type Description struct {
	ID              int64
	DescriptionText sql.NullString
}

type TranCode struct {
	ID   int64
	Code sql.NullString
}

type Transaction struct {
	ID            int64
	Date          sql.NullString
	Amount        sql.NullFloat64
	DescriptionID sql.NullInt64
	CodeID        sql.NullInt64
	Foreign       interface{}
}
